### ISSUE TITLE
The following unpacked files (in .json format)

### ISSUE THREAD

**Issue by Aefis** [YounesM/DofusBot#1]
Hye,
What do you mean by that?
Where can I find those files if they do exist?

"The following unpacked files (in .json format):
Recipes.d2o
Items.d2o
Effects.d2o
i18n_.d2i"

It may be evident but I didn't understand.
Sorry, I have just joined this website.

Thank you for your help

**Comment by YounesM** [comment]
You can find them in : /Ankama/Dofus/app/data/common
